#!/usr/bin/env python3

ver = '1.0-ALPHA'

import sys
import os

os.system('clear')

home = os.environ['HOME']

sys.path.append(home + '/PTEC/base/lib')

try:
    import ptlib
    ptlib.log('PTLIB Imported!')
except ImportError:
    print('Cant import ptlib. Is PTEC System installed?')
    exit()

try:
    import ptlib_ptpc_emu
    ptlib.log('ptlib_ptpc_emu Imported!')
except ImportError:
    print('Cant import ptlib_ptpc_emu. Is ptlib_ptpc_emu installed?')
    print('You could run \'ptlib_ptpc_emu\' to fix this')
##################################################

ptpcEmuPath = home + '/PTEC/PTPC-Emu/'
ptpcEmuROM = ptpcEmuPath + 'ROM'
ptpcEmuMEM = ptpcEmuPath + 'MEM'

mode = 'PTIS-8BITS'
decMode = 'NORMAL'
skip = 0

MP = 0 #Memory Pointer
FLAGS = 0 #FLAGS
A = 0 #A
B = 0 #B
C = 0 #C
FRAME = 0

def GUI():
    ptlib.log('No GUI Implimented Yet! Exiting...')
    exit()

def decode(value):
    global skip
    global ROM
    global MP
    global FLAGS
    global A
    global B
    global C
    value1 = ROM[MP + 1]
    value2 = ROM[MP + 2]
    value3 = ROM[MP + 3]
    value1_2 = ROM[MP + 1] + ROM[MP + 2]
    skip = 0
    if value == 0:
        ...
    if value == 1:
        print('(ADDRESS: ' + str(MP) + ', FRAME: ' + str(FRAME) + ') Adding: ' + str(value2) + ' To Address: ' + str(value1_2))
        ramIndex = value1_2 - 255
        print(str(value1_2) + ' ramIndex: ' + str(ramIndex))
        #ptlib_ptpc_emu.writeMEM(value1_2 - 256, ptlib_ptpc_emu.readMEM(value1_2, ptpcEmuMEM) + value2, ptpcEmuMEM)
        skip = 4
    if value == 2:
        print('ADDA')
        skip = 2
    elif value > 19:
        print('INVALID: ' + str(value))
    

args = sys.argv
if len(args) > 1:
    ...
else:
    #ptlib.log('No commands parsed. Starting GUI')
    #GUI()
    ptlib.log('Running PTPC Emulator with default settings:\n' + 'Mode:' + mode + '\n\nDecode Mode:' + decMode)
    
ROM = ptlib_ptpc_emu.getROM(ptpcEmuROM)
ROMlen = len(ROM)
MEMlen = len(ptlib_ptpc_emu.getMEM(ptpcEmuMEM))
print('Rom Is ' + str(ROMlen) + ' Bytes Long')
print('Mem Is ' + str(MEMlen) + ' Bytes Long')
print('Total Memory: ' + str(ROMlen + MEMlen) + '\n')

ptlib_ptpc_emu.writeMEM(0, 255, ptpcEmuMEM)

if decMode == 'NORMAL':
    while True:
        if MP < ROMlen - 3:
            FRAME = FRAME + 1
            value = ROM[MP]
            #print('MP=' + str(MP) + ' Value = ' + str(value) + '(HEX: ' + hex(value) + ')')
            decode(value)
            MP = MP + 1 + skip
        else:
            ptlib.log('Execution Ended')
            break
