#!/usr/bin/env python3

ver = 'DEVELOPMENT'

print('\n     PTEC Pakage Manager | Version: ' + ver + '\n')

import sys
import os

def installerUI():
    print('Installer UI Is Not Yet Implimented!, Exiting')
    exit()

def decode(cmd):
    if cmd == 'install' or cmd == 'i':
        if options[0]:
            ptlib.log('Calling ptpkglib Install() for package: ' + options[1])
            ptpkglib.Install(options[1])
        else:
            ptlib.log('No Package Specified. Exiting')
            exit()
    elif cmd == 'remove' or cmd == 'r':
        if options[0]:
            ptlib.log('Calling ptpkglib Remove() For Package: ' + options[1])
            ptpkglib.Remove(options[1])
        else:
            ptlib.log('No Package Specified. Exiting')
            exit()
    else:
        ptlib.log('Invalid Command: ' + cmd + '\nUse Command \'help\' For a List Of Avalible Commands')
try:
    home = os.environ['HOME']
    sys.path.append(home + '/PTEC/base/lib')
    import ptpkglib
except ModuleNotFoundError:
    ptlib.log('Error: Could Not Import ptpkglib, Exiting')
    exit()
try:
    home = os.environ['HOME']
    sys.path.append(home + '/PTEC/base/lib')
    import ptlib
except ModuleNotFoundError:
    ptlib.log('Error: Could Not Import ptlib, Exiting')
    exit()

ptlib.log('Modules ptlib and ptpkglib successfully loaded!')

if len(sys.argv) < 2:
    ptlib.log('No Commands Parsed! Starting UI!')
    installerUI()
else:
    options = sys.argv[1:]
    command = options[0]

decode(command)
